spring:
  application:
    name: customer-service
    
server:
  servlet:
    context-path: /v1
     
db:
  dbName: localDBName
  dbUser:  localDBUser
  dbPassword: localDBPassword

feign:
  client: 
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false
    
service: 
    order_service:
      name: order-service
      url: http://localhost:8080

#server.port: 8081
  
  
 