apiVersion: apps/v1
kind: Deployment
metadata: 
  name: customer-service
  labels: 
    app: customer-service
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: customer-service
  template: 
    metadata: 
      labels: 
        app: customer-service
    spec: 
  #    hostAliases:
  #      - ip: "192.168.99.103"
  #        hostnames:
  #          - "kubeall.com"
      containers:
      - name: customer-service
        image: med/customer-service:1.0
        imagePullPolicy: Never
        volumeMounts: 
        - name: secret-volume
          mountPath: /etc/secret-volume
        ports: 
        - containerPort: 8080
        env:
        - name: DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: microservice-k8s-configmap
              key: customer-database-name
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: microservice-k8s-secret
              key: customer-database-user
      volumes: 
          - name: secret-volume
            secret: 
                secretName: microservice-k8s-secret
                items:
                  - key: customer-database-user
                    path: customer_user 
                  - key: customer-database-password
                    path: customer_password 
---    
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 30004
  type: LoadBalancer