spring:
  application:
    name: customer-service
 
db:
  dbName: ${DB_NAME}
  dbUser:  ${DB_USER}
  dbPassword: /etc/secret-volume/customer_password

feign:
  client: 
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false
    
service: 
    order_service:
      name: order-service
      url: http://localhost:8080/

server: 
  port: 8081
  
  
 