spring:
  application:
    name: order-service
    
server:
  servlet:
    context-path: /v1
 
db:
  dbName: localDBName
  dbUser:  localDBUser
  dbPassword: localDBPassword
  
service: 
    customer_service:
      host: http://localhost:8081
       
#server.port: 8080
  